version: '3.8'

# volumes:
#   staging-volume:

services:
  bob_node:
    container_name: subtensor-staging-net-bob
    image: 891377275001.dkr.ecr.us-east-1.amazonaws.com/localnet_images:latest
    build:
      context: .
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    # volumes:
    #   - staging-volume:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain/bob \
          --chain stagingSpec.json \
          --bob \
          --port 30333 \
          --rpc-external \
          --ws-external \
          --validator \
          --rpc-cors=all \
          --rpc-methods=unsafe \
          --allow-private-ipv4 \
          --discover-local

  alice_node:
    container_name: subtensor-staging-net-alice
    image: 891377275001.dkr.ecr.us-east-1.amazonaws.com/localnet_images:latest
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    ports:
      - "9945:9944"
      - "30334:30333"
      - "9934:9934"
    expose:
      - "9945"
      - "30334"
      - "9934"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    # volumes:
    #   - staging-volume:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain/alice \
          --chain stagingSpec.json \
          --alice \
          --port 30333 \
          --rpc-external \
          --ws-external \
          --validator \
          --rpc-cors=all \
          --rpc-methods=unsafe \
          --allow-private-ipv4 \
          --discover-local

  local_staging_node:
    #  This node cannot be run at the same time as the containers above.
    container_name: subtensor-staging-net-local_node
    image: stagingnet:v1.0
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    ports:
      - "9946:9944"
      - "30337:30333"
      - "9938:9933"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
      - NODE_IP=${NODE_IP:-default_ip}
      - NODE_ID=${NODE_ID:-default_id}
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/node01 \
          --chain stagingSpec.json \
          --name node01 \
          --port 30333 \
          --rpc-external \
          --ws-external \
          --rpc-cors=all \
          --rpc-methods=unsafe \
          --allow-private-ipv4 \
          --discover-local
        
        
    # --bootnodes /ip4/${NODE_IP}/tcp/30333/p2p/${NODE_ID}
